### ISSUE TITLE
Fix for 7U3g

### ISSUE THREAD

**Issue by Systm21** [netgc/esxi-unlocker-4#1]
Hello @netgc ,
is it possible to fix the unlocker for the last Version of ESXi or for U3 mainly? On Workstation it works, but on Esxi it boots, but get stuck on the half.

greetings

**Comment by netgc** [comment]
[esxi-unlocker-4](https://github.com/netgc/esxi-unlocker-4) support ESXi only，work well on ESXi 7 & 8, it does not support
 Workstation。please download  ESXi iso image (integrated Unlocker and SLIC) to install.
